backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "GithubID", name: "githubId", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "CanvasData"
    label: "CanvasData"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "data"
        label: "Site data"
        file: "src/pages/canvas/data.json"
        description: "General Site data"
        fields:
          - label: "nodes"
            name: nodes
            widget: "object"
            fields:
              - {
                  label: "Id of the page",
                  name: id,
                  widget: string,
                  required: true,
                }
              - {
                  label: "Default group",
                  name: group,
                  widget: string,
                  required: true,
                }
              - {
                  label: "Default type",
                  name: type,
                  widget: string,
                  required: true,
                }
              - {
                  label: "Order",
                  name: order,
                  widget: number,
                  min: 1,
                  required: true,
                }
              - {
                  label: "Url to file",
                  name: url,
                  widget: string,
                  required: true,
                }
              - {
                  label: "linked files",
                  name: to,
                  widget: string,
                  required: true,
                }
